<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Main' => 'Главная',
    'Sitemap' => 'Карта сайта',
    'Auto Insurance' => 'Автострахование',
    'Health Insurance' => 'Здоровье',
    'Property Insurance' => 'Недвижимость',
    'Responsibility Insurance' => 'Ответственность',
    'OSAGO' => 'ОСАГО',
    'KASKO' => 'КАСКО',
    'Greencard' => 'Зеленая карта',
    'Tourism' => 'Туризм',
    'Med Insurance' => 'Медицинское страхование',
    'Accident' => 'Несчастный случай',   
    'Appartment' => 'Квартира',
    'House' => 'Частный дом',
    'Country house' => 'Дача',
    'About' => 'О нас',
    'For business' => 'Для бизнеса',
    'Insurance companies' => 'Страховые компании',
];

