<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'tip_ts' => 'Тип авто',
    'legkovye_ts_do_1600_sm3' => 'Легковые ТС до 1600 см3',
    'legkovye_ts_1601_2000_sm3' => 'Легковые ТС 1601-2000 см3',
    'legkovye_ts_2001_3000_sm3' => 'Легковые ТС 2001-3000 см3',
    'legkovye_ts_3001_sm3_i_bolshe' => 'Легковые ТС 3001 см3 и больше',
    'pritsepy_k_legkovym_ts' => 'Прицепы к легковым ТС',
    'gruzovye_ts_do_2t' => 'Грузовые ТС до 2т',
    'gruzovye_ts_2t_i_bolshe' => 'Грузовые ТС 2т и больше',
    'pritsepy_k_gruzovym_ts' => 'Прицепы к грузовым ТС',
    'avtobusy_do_20_mest' => 'Автобусы до 20 мест',
    'avtobusy_20_i_bolee_mest' => 'Автобусы 20 и более мест',
    'mototsikly_do_300_sm3' => 'Мотоциклы до 300 см3',
    'mototsikly_300_sm3_i_bolshe' => 'Мотоциклы 300 см3 и больше',

    'mesto_registratsii' => 'Регистрация авто по техпаспорту',
    'zona_1_kiev' => 'Зона 1 (Киев)',
    'zona_2_borispol_boyarka_brovari_vasilkov_vishgorod_vishnevoe_irpen' => 'Зона 2 (Борисполь, Боярка, Бровари, Васильков, Вишгород, Вишнёвое, Ирпень)',
    'zona_3_odessa_kharkov' => 'Зона 3 (Одесса, Харьков)',
    'zona_4_dnepropetrovsk_donetsk_zaporozhe_krivoy_rog_lvov' => 'Зона 4 (Днепропетровск, Донецк, Запорожье, Кривой Рог, Львов)',
    'zona_5' => 'Зона 5',
    'zona_6_nas_punkty_menee_100_tys_chel' => 'Зона 6 (нас пункты менее 100 тыс чел)',
    'zona_7_inye_strany' => 'Зона 7 (иные страны)',

    'franshiza' => 'Франшиза',
    '0' => '0',
    '510' => '510',
    '2000' => '2000',
    '1000' => '1000',
    
    'sfera_ispolzovaniya' => 'Сфера использования',
    'fiz_litso' => 'Физ. лицо',
    'fiz_litso_taksi' => 'Физ лицо - такси',
    'yur_litso' => 'Юр. лицо',
    'yur_litso_taksi' => 'Юр лицо - такси',
    
    'stazh_vozhdeniya' => 'Стаж вождения',
    'do_3_kh_let' => 'Стаж до 3-х лет',
    'bolee_3_kh_let' => 'Стаж более 3-х лет',
    
    'srok_deystviya' => 'Срок действия договора',
    '1_god' => '1 год',
    '11_mesyatsev' => '11 месяцев',
    '10_mesyatsev' => '10 месяцев',
    '9_mesyatsev' => '9 месяцев',
    '8_mesyatsev' => '8 месяцев',
    '7_mesyatsev' => '7 месяцев',
    '6_mesyatsev' => '6 месяцев',
    '5_mesyatsev' => '5 месяцев',
    '4_mesyatsa' => '4 месяца',
    '3_mesyatsa' => '3 месяца',
    '2_mesyatsa' => '2 месяца',
    '1_mesyats' => '1 месяц',
    '15_dney' => '15 дней',    
    
    'god_vypuska_bm' => 'Год выпуска автомобиля',
    '2016' => '2017',
    '2015' => '2016',
    '2014' => '2015',
    '2013' => '2014',
    '2012_i_ranee' => '2013 и ранее',     

    'kolichestvo_ts' => 'Количество ТС',
    '1_4_ts' => '1 - 4 ТС',
    '5_9_ts' => '5 - 9 ТС',
    '10_19_ts' => '10 - 19 ТС',
    '20_99_ts' => '20 - 99 ТС',
    '100_499_ts' => '100 - 499 ТС',
    '500_1999_ts' => '500 - 1999 ТС',
    '2000_i_bolee_ts' => ' 	2000 и более ТС',      
    
    'lgoty' => 'Льготы',
    'net_lgot' => 'Нет льгот',
    'est_lgoty' => 'Пенсионер',    
    'chernobylets_14' => 'Чернобылец I или II групп',    
    'invalid_14' => 'Инвалид II группы',    
    'uchastnik_voyny_14' => 'Участник войны',    
    
    'vyberite_vash_gorod' => 'Выберите Ваш город',
    'ukazhite_gorod_registratsii_avto' => 'Укажите город регистрации авто',
    
    // Greencard
    
    'zk_srok_deystviya' => 'Срок действия',
    '1_god_25' => '1 год',
    '11_mesyatsev_25' => '11 месяцев',
    '10_mesyatsev_25' => '10 месяцев',
    '9_mesyatsev_25' => '9 месяцев',
    '8_mesyatsev_25' => '8 месяцев',
    '7_mesyatsev_25' => '7 месяцев',
    '6_mesyatsev_25' => '6 месяцев',
    '5_mesyatsev_25' => '5 месяцев',
    '4_mesyatsa_25' => '4 месяца',
    '3_mesyatsa_25' => '3 месяца',
    '2_mesyatsa_25' => '2 месяца',
    '1_mesyats_25' => '1 месяц',
    '15_dney_25' => '15 дней',
    
    'zk_tip_ts' => 'Тип ТС',
    'legkovye_ts_24' => 'Легковые ТС',
    'avtobusy_24' => 'Автобусы',
    'gruzovye_ts_24' => 'Грузовые ТС',
    'pritsepy_24' => 'Прицепы',
    'mototsikly_24' => 'Мотоциклы',
    
    'zk_napravlenie' => 'Направление',
    'azer_bel_mol_ros_23' => 'Азербайджан, Белоруссия, Молдова, Россия',
    'evropa_23' => 'Европа',
    
    // Tourism
    
    'country' => 'Направление',
    'insurance_sum' => 'Страховая сумма по здоровью',
    'ns_insurance_sum' => 'Несчастный случай',
    'purpose' => 'Цель поездки',
    'transport' => 'Способ передвижения',
    
    'turizm' => 'Туризм',
    'aktivnyy_otdykh' => 'Активный отдых',
    'lyubitelskiy_sport' => 'Любительский спорт',
    'professionalnyy_sport' => 'Профессиональный спорт',
    'intellektualnyy_trud' => 'Интеллектуальный труд',
    'fizicheskiy_trud' => 'Физический труд',
    'travel_business' => 'Туризм, бизнес поездка ',
    
    'usd_10000' => '10 000 USD',
    'usd_30000' => '30 000 USD',
    'usd_50000' => '50 000 USD',
    'eur_50000' => '50 000 EUR',
    'eur_30000' => '30 000 EUR',
    'usd_60000' => '60 000 USD',
    'eur_60000' => '60 000 EUR',
    'usd_1000' => '1 000 USD',
    'eur_1000' => '1 000 EUR',
    'usd_2000' => '2 000 USD',
    'eur_2000' => '2 000 EUR',
        
    
    'velikobritaniya' => 'Великобритания',
    'germaniya' => 'Германия',
    'italiya' => 'Италия',
    'frantsiya' => 'Франция',
    'italiya' => 'Италия',
    'bolgariya' => 'Болгария',
    'azerbaydzhan' => 'Азербайджан',
    
    'samoletompoezdommorem' => 'Самолетом/Поездом/Морем',
    'na_avtomobileavtobuse' => 'На автомобиле/автобусе',
    'na_mototsikle' => 'На мотоцикле',
    'lyubym_sposobom' => 'Любым способом',
    
    'company_bonuses' => 'Бонусы',
    
     // Moto-kasko
    
    'moto_age' => 'Возраст мотоцикла',
    'moto_srok_deystviya' => 'Срок действия',
    'moto_market_price' => 'Рыночная стоимость, грн',
    
    'up_to_5_y_27' => 'До 5 лет',
    '5_10_y_27' => '5-10 лет',
    '3_month_28' => '3 месяца',
    '6_month_28' => '6 месяцев',
    '9_month_28' => '9 месяцев',
];

