<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Main' => 'Головна',
    'Sitemap' => 'Мапа сайту',
    'Auto Insurance' => 'Автострахування',
    'Health Insurance' => 'Здоров`я',
    'Property Insurance' => 'Нерухомість',
    'Responsibility Insurance' => 'Відповідальність',
    'OSAGO' => 'ОСЦПВ',
    'KASKO' => 'КАСКО',
    'Greencard' => 'Зелена карта',
    'Tourism' => 'Туризм',
    'Med Insurance' => 'Медичне страхування',
    'Accident' => 'Нещасний випадок',    
    'Appartment' => 'Квартира',
    'House' => 'Приватний будинок',
    'Country house' => 'Дача',
    'About' => 'Про нас',
    'For business' => 'Для бізнесу',
    'Insurance companies' => 'Страхові компанії',
];

